// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp.net.LearningProject.Data;

namespace asp.net.LearningProject.Migrations
{
    [DbContext(typeof(MyProjectDBContext))]
    [Migration("20191017123139_relationshipAndseed")]
    partial class relationshipAndseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("asp.net.LearningProject.Models.AdressModels.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Region");

                    b.HasKey("TownId");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            TownId = 1,
                            Name = "Town1",
                            Region = "Region1"
                        },
                        new
                        {
                            TownId = 2,
                            Name = "Town3",
                            Region = "Region2"
                        },
                        new
                        {
                            TownId = 3,
                            Name = "Town3",
                            Region = "Region3"
                        });
                });

            modelBuilder.Entity("asp.net.LearningProject.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("TownId");

                    b.HasKey("EmployeeId");

                    b.HasIndex("TownId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Department = 4,
                            Email = "george@email.com",
                            Name = "George",
                            TownId = 2
                        },
                        new
                        {
                            EmployeeId = 2,
                            Department = 1,
                            Email = "pesho@email.com",
                            Name = "Pesho",
                            TownId = 1
                        });
                });

            modelBuilder.Entity("asp.net.LearningProject.Models.Employee", b =>
                {
                    b.HasOne("asp.net.LearningProject.Models.AdressModels.Town", "Town")
                        .WithMany("Employees")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
